### ISSUE TITLE
Wiring of the stepper

### ISSUE THREAD

**Issue by kalsan** [d235j/AccelStepper#1]
Hi there! I tried out your AccelStepper library and I'm very impressed, it's extremely smooth!

I took an old Siemens 1BC2826-6AD out of an electrical typewriter. It has six wires coming out of two separate locations in the motor (each location has red, brown and black). After lots of experimenting, I found that I can run it in bipolar mode ordering the cables as follows: (`P1-4`): redA, brownB, brownA, redB (black unconnected). Doing so, the sequence described in binary numbers in the image below is as follows:

![Image described above](http://ebldc.com/wp-content/uploads/2010/09/BipolarPhases.jpg)

```
void a(int pm){
  if(pm>0){
    digitalWrite(P1, HIGH);
    digitalWrite(P3, LOW);
  }else{
    digitalWrite(P1, LOW);
    digitalWrite(P3, HIGH);
  }
}

void b(int pm){
  if(pm>0){
    digitalWrite(P2, HIGH);
    digitalWrite(P4, LOW);
  }else{
    digitalWrite(P2, LOW);
    digitalWrite(P4, HIGH);
  }
}

void doStep(int st){
  switch(st){
    case 0:
    a(1);
    b(1);
    break;
    case 1:
    a(1);
    b(0);
    break;
    case 2:
    a(0);
    b(0);
    break;
    case 3:
    a(0);
    b(1);
    break;
  }
}

void forward(){
  step = (step+1) % 4;
  doStep(step);
}

void backward(){
  step = (step+3) % 4;
  doStep(step);
}
```

Passing these forward and backward functions to the AccelStepper library makes the motor run super nicely. However I cannot find a working default constructor (e.g. `FULL4WIRES` does not work).

Did I wire my stepper in a wrong way or is it a particular stepper that is not covered by the library?

**Comment by d235j** [comment]
@kalsan Just so you're aware this is a mirror. As described in the README, the original author website is at http://www.airspayce.com/mikem/arduino/AccelStepper/ . I suggest directing questions there.

It wouldn't surprise me if this is a stepper that's not covered by this library; again I suggest reaching out to the upstream developer for help.

**Comment by kalsan** [comment]
Thanks for your fast reaction and sorry for my negligence, I should go to bed. I'll get in touch with the author when awake.
